### PR TITLE
Enhanced and corrected probability chapter

### PR DESCRIPTION
**Pull request by aradnix**
I reviewed the whole chapter about probability, and among the changes I made are the following:
added the chapter title to the file:

1. I changed the definition of all the equations displayed out of paragraph using the equation* environment from the `amsmath` package for 2 reasons:
a. gives more legibility to the code and 
b. allows the equations to be numbered, if necessary if at any point in the development of the book it is considered necessary
2. I rewrote several equations according to the `amsmath` features and added some operator and comments about them
3. I also corrected some spelling errors that I found throughout the chapter.

### CODE REVIEW

**Comment by RicardoHS** [comment]
I havent check the full changes yet but they look very promising. 

Anyway, you have created two pull request, if you want to change anything, just commit to the other pull request and close this one. [Also I have created another branch](https://github.com/RicardoHS/statistics-for-data-science-book/tree/issue-7-create_a_good_layout-merge) to perform the merge and avoid unnecesary git log.

FInally, this last build have fail. You can check the output [here](https://travis-ci.com/RicardoHS/statistics-for-data-science-book/builds/134528107)

My recommendation is to try to fix it and pull it to the other pull request. It is not a good practice to open another pull request to fix/add anything if the other pull request have not been merged yet.

**Comment by RicardoHS** [comment]
Changed the base branch to merge to use the correct one

**Comment by RicardoHS** [comment]
I have tried to fix some of the errors of this merge but it was impossible for me. Some errors arise from new packages for me. I need to gain more knowledge about this. Until then, I will leave this merge open.

**Comment by aradnix** [comment]
Well, I've been reading the scarce tectonic documentation that's available.
I already checked its website about the installation options and after
several failed attempts I finally achieved to install it locally on my
computer.

It had to be from conda, because the other options simply couldn't install
anything called tectonic.

Right now I'm trying to compile your book but it seems that tectonic has to
check aaaaaall my local TeXlive installation files prior to that and it
took more than 10 minutes until it broke and threw an error related with
todonotes package.

So far it's been a pain in the ass.

What I'm going with is that I'd like you to explain me how you're using
tectonic, what commands and options you use. Also although I don't have so
much experience with docker, last summer I was able to use a container for
a basic data science course, so maybe I can replicate your workflow on my
machine, I use Linux Mint 19.1.

Regards

**Comment by RicardoHS** [comment]
If you are using linux, then the use of docker is very straighforward.

First of all you need to check if docker is installed. Run `docker` in the terminal and if it show the help of docker then it is installed. In case not, just follow [this guide](https://linuxhint.com/install_docker_linux_mint/) for linux mint.

Once docker is installed, you can clone the repo (`git clone https://github.com/RicardoHS/statistics-for-data-science-book.git`) in any path you like `cd` from the terminal to the path (something like `cd /home/user/git/statistics-for-data-science-book/`) and then write in the terminal `./scripts/build/build_local.sh`

In case no output error, then you will have a main.pdf file inside the src folder. In case of any error, you can run manually the command

`docker run -it -v .:/data dxjoke/tectonic-docker bash /data/scripts/docker/docker_tex.sh`

This last command is more likely to fail, because right now the build process is a little bit more complicated than just running that command.

In any case, try that and let me know what is your result.

edit: remember to have internet connection in order to let docker download the tectonic image

**Comment by aradnix** [comment]
Well, thank you for your reply.

I will try to respond punctually to each of the things you have explained
to me:

1. I have Docker installed, the version I have is: 18.09.7, build 2d0083d

2. Some time ago I cloned your repository and I remember that I executed a
script to generate the version and other things but I don't remember
exactly what it was. I did it again but I used cd to move to
the ..git/statistics-for-data-science-book/scripts/build/ directory, and
once inside I typed sud build_local.sh and I don't know what dark magic
invoked that thing that loaded tectonic from the docker container as far as
I can see and now it's again checking all the packages in the Main.tex file
and running everything without me having explicitly written tectonic into
the terminal with its flags and options.

3. In the end the result was this:
Status: Downloaded newer image for dxjoke/tectonic-docker:latest
note: this is a BETA release; ask questions and report bugs at
https://tectonic.newton.cx/
Running TeX ...
note: indexing
https://archive.org/services/purl/net/pkgwpub/tectonic-default
note: resolved to
https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar
note: downloading SHA256SUM
note: downloading scrbook.cls
note: downloading scrkbase.sty
note: downloading scrbase.sty
note: downloading scrlfile.sty
note: downloading tocbasic.sty
note: downloading scrsize12pt.clo
note: downloading typearea.sty
note: downloading inputenc.sty
note: downloading fontenc.sty
note: downloading t1lmr.fd
note: downloading ec-lmr12.tfm
note: downloading babel.sty
note: downloading english.ldf
note: downloading babel.def
note: downloading txtbabel.def
note: downloading csquotes.sty
note: downloading csquotes.def
note: downloading csquotes.cfg
note: downloading FiraSans.sty
note: downloading textcomp.sty
note: downloading ts1enc.def
note: downloading fontspec.sty
note: downloading xparse.sty
note: downloading expl3.sty
note: downloading expl3-code.tex
note: downloading CaseFolding.txt
note: downloading SpecialCasing.txt
note: downloading l3xdvipdfmx.def
note: downloading fontspec-xetex.sty
note: downloading fontspec.cfg
note: downloading FiraSans-Regular.otf
note: downloading FiraSans-Bold.otf
note: downloading FiraSans-RegularItalic.otf
note: downloading FiraSans-BoldItalic.otf
note: downloading FiraSans-Thin.otf
note: downloading FiraSans-ThinItalic.otf
note: downloading FiraSans-Light.otf
note: downloading FiraSans-LightItalic.otf
note: downloading FiraSans-ExtraLight.otf
note: downloading FiraSans-ExtraLightItalic.otf
note: downloading FiraSans-UltraLight.otf
note: downloading FiraSans-UltraLightItalic.otf
note: downloading FiraSans-Medium.otf
note: downloading FiraSans-MediumItalic.otf
note: downloading FiraSans-Book.otf
note: downloading FiraSans-BookItalic.otf
note: downloading FiraSans-SemiBold.otf
note: downloading FiraSans-SemiBoldItalic.otf
note: downloading FiraSans-ExtraBold.otf
note: downloading FiraSans-ExtraBoldItalic.otf
note: downloading FiraSans-Heavy.otf
note: downloading FiraSans-HeavyItalic.otf
note: downloading FiraMono.sty
note: downloading FiraMono-Regular.otf
note: downloading FiraMono-Bold.otf
note: downloading FiraMono-Medium.otf
note: downloading mathtools.sty
note: downloading mhsetup.sty
note: downloading mathfixs.sty
note: downloading booktabs.sty
note: downloading multicol.sty
note: downloading tcolorbox.sty
note: downloading environ.sty
note: downloading trimspaces.sty
note: downloading todonotes.sty
note: downloading tikzlibrarypositioning.code.tex
note: downloading ts1cmr.fd
note: downloading cmr17.tfm
note: warnings were issued by the TeX engine; use --print and/or
--keep-logs for details.
Running xdvipdfmx ...
Writing src/main.pdf (17669 bytes)
Writing src/main.bcf (90112 bytes)
Writing src/main.run.xml (2342 bytes)
Not writing main.tdo: it would be empty.
Writing src/chapters/preface.aux (4224 bytes)
Writing src/main.out (43 bytes)
Writing src/main.toc (225 bytes)
Writing src/main.aux (1166 bytes)
INFO - This is Biber 2.11
INFO - Logfile is 'src/main.blg'
INFO - Reading 'src/main.bcf'
INFO - Found 0 citekeys in bib section 0
WARN - The file 'src/main.bcf' does not contain any citations!
INFO - Writing 'src/main.bbl' with encoding 'UTF-8'
INFO - Output to src/main.bbl
INFO - WARNINGS: 1
note: this is a BETA release; ask questions and report bugs at
https://tectonic.newton.cx/
Running TeX ...
note: warnings were issued by the TeX engine; use --print and/or
--keep-logs for details.
Rerunning TeX because "main.run.xml" changed ...
Rerunning TeX because "main.run.xml" changed ...
Rerunning TeX because "main.run.xml" changed ...
Rerunning TeX because "main.run.xml" changed ...
Rerunning TeX because "main.run.xml" changed ...
Rerunning TeX because "main.run.xml" changed ...
warning: TeX rerun seems needed, but stopping at 6 passes
Running xdvipdfmx ...
Writing src/main.pdf (17970 bytes)
Writing src/main.bcf (90112 bytes)
Skipped writing 6 intermediate files (use --keep-intermediates to keep them)

4. And although it seems to work well locally on my computer, I still don't
understand how it works, and I'm not used to working like this, when I
build directly with pdflatex I get a lot of feedback that allows me to
understand if there is an error and where to find it but here the messages
I get are not so clear.

I stay on top of it so I can learn how to work with tectonic and get on
with the project.

Regards

**Comment by RicardoHS** [comment]
Good news. It's working as expected. The build.sh script remove all the intermediate files that tectonic creates (I think they are the same that pdflatex creates).

The way docker works, in this case, is that it creates a 'virtual machine' inside your computer and executes tectonic inside it. It store all the files in the folder `src` and when it finish the 'virtual machine' is destroyed. 

Idk what is the output of pdflatex, but I can tell you that when something is wrong with tectonic it said where is the error.

[More info about what is executed inside the docker](https://hub.docker.com/r/dxjoke/tectonic-docker)

Returning to the build error, the exact error is in the line 22 of the probability.tex file
```
(chapters/probability [11] [12]

Chapter 3.

! Undefined control sequence.

l.22 and his elements can be denoted by\didit

                                             {If you are going to put a disp...
```

**Comment by aradnix** [comment]
Okay, I'm getting the hang of how tectonic works.

Yesterday I was doing tests, building chapter by chapter from the prologue
to chapter 3 that I haven't finished reviewing. And in no case I had
errors, however the truth is that tectonic is extremely slow.
So tectonic takes 7 minutes and 42 seconds to compile the same document
that LatexMk compiles in 30 seconds and pdflatex in 8 seconds (considering
the 2 passes it requires to update table of content, another indexes and
cross-references), in all cases 94 pages and 689933 bytes were processed.
That's annoying for me, although a little less now that you've told me how
to review the errors that tectonic throws. Anyway in my computer I have not
obtained any compilation error in chapter 2 which is the one I have worked
most.

Regards

**Comment by RicardoHS** [comment]
The build time is probably due the fact that tectonic downloads all libraries in each execution. It's not because tectonic, it's because docker. Let me check if a custom docker image can be easily build with all these dependencies, and if by doing so the build time heavily decrease

**Comment by aradnix** [comment]
Something like that I thought, that could influence the fact that I was
using a container, however in the previous attempts with the local
installation that I made from conda it still took almost 10 minutes to
build, with the difference that I finished the process in error.

It's not the processing time that worries me the most, even though the
difference is huge compared to the usual builders I use.

I'm more concerned about the fact that it doesn't throw errors at me when
compiling and it does at you.

**Comment by RicardoHS** [comment]
I think the output is the same. As far as I have see, the logs you have show me are the same for me.

**Comment by aradnix** [comment]
Well, then the output pdf should be the same without errors, something like
this:

**Comment by RicardoHS** [comment]
Something like empty output? xD

**Comment by aradnix** [comment]
I don't think so...

That's why this seems weird to me. I don't know if my TeXlive installation
is related.

**Comment by RicardoHS** [comment]
No no, I mean, that in your last comment you haven't attached any output at all hahaha

**Comment by aradnix** [comment]
Weird, the file I attached is a pdf with contents. The same one in the
screenshot.

**Comment by RicardoHS** [comment]
well, I think you cannot attach files to this kind of emails. You are answering to notifications@github.com not to me directly. Idk if you are aware, but this conversation is public here https://github.com/RicardoHS/statistics-for-data-science-book/pull/27

**Comment by aradnix** [comment]
That should be the reason, thanks for clarifying it.

**Pull request closed without merging**
